### ISSUE TITLE
JSX element type 'TextareaAutosize' is not a constructor function for JSX elements.

### ISSUE THREAD

**Issue by szabolcsx** [buildo/react-autosize-textarea#56]
The following error is thrown when trying to compile a project using the autosize textarea component with Typescript 2.3.4:
error TS2605: JSX element type 'TextareaAutosize' is not a constructor function for JSX elements.

The fix is simple:
``` JSX
// export default class TextareaAutosize extends React.Component<TextareaAutosizeProps, void> {}
export default class TextareaAutosize extends React.Component<TextareaAutosizeProps, {}> {}
```
Can this be included in the next version?

**Comment by FrancescoCioria** [comment]
Hi @szabolcsx 
mmmm this is strange because we've been using TextareaAutosize successfully in Typescript projects..

I tried to reproduce your bug and I noticed that it appears only if you import the component with the `* as` syntax. Is it possible?

Anyway, the `index.d.ts` is clearly reflecting `lib/index.js` instead of `index.js` which is an error.
I'll try to fix it asap.

Thank you for reporting this issue!

**Comment by szabolcsx** [comment]
Hi @FrancescoCioria 
I recently my TypeScript compiler to version 2.3.4. It was working with the version 2.2.2.

I am importing the component in the following way:
``` JSX
import Textarea from "react-autosize-textarea";
```
This is the full error message thrown by the compiler:
```
error TS2605: JSX element type 'TextareaAutosize' is not a constructor function for JSX elements.
  Types of property 'setState' are incompatible.
    Type '{ <K extends never>(f: (prevState: void, props: TextareaAutosizeProps) => Pick<void, K>, callback...' is not assignable to type '{ <K extends never>(f: (prevState: {}, props: an
y) => Pick<{}, K>, callback?: () => any): void; <...'.
      Types of parameters 'f' and 'f' are incompatible.
        Type '(prevState: {}, props: any) => Pick<{}, any>' is not assignable to type '(prevState: void, props: TextareaAutosizeProps) => Pick<void, any>'.
          Types of parameters 'prevState' and 'prevState' are incompatible.
            Type 'void' is not assignable to type '{}'.
```

This is possibly caused by this line in the `React.Component` class:
``` JSX
state: Readonly<S>;
```

By the looks of it, `Readonly<T>` expects` T` to be an object:
``` JSX
/**
 * Make all properties in T readonly
 */
type Readonly<T> = {
    readonly [P in keyof T]: T[P];
};
```

I think we can entirely leave out the second type parameter (`void`) with TypeScript 2.3.4 and newer:
``` JSX
interface Component<P = {}, S = {}> extends ComponentLifecycle<P, S> { }
```

As you can see, type parameters can have a default type now.
The declaration of `TextareaAutosize` class could be simplified to the following:
``` JSX
export default class TextareaAutosize extends React.Component<TextareaAutosizeProps> {}
```
Which would evaluate to:
``` JSX
export default class TextareaAutosize extends React.Component<TextareaAutosizeProps, {}> {}
```

**Comment by FrancescoCioria** [comment]
Ok, I investigated this error and it's caused by two issues:
1. `index.d.ts` does an `export default` but currently it's referring to `index.js` which does `module.exports = require('./lib')` so they are inconsistent (I don't know how it worked so far 😕 )
2. The state is not `void` anymore (it was until #50) but...
3. ...`index.d.ts` should type only TextareaAutosize's API so it shouldn't expose the state at all!

I'll try to fix it asap

**Comment by FrancescoCioria** [comment]
I just released `0.4.7` with the fix from #58
